export const PROJECTS = [
  // Vídeo hospedado no próprio site (sem YouTube): use `video` no lugar de `url`.
  // `preview`: caminho sem extensão de um loop curto (.webm VP9 + .mp4 H.264, 6 s, 960×540, sem áudio) — ver README.
  { id: 25, date: "2026-09-23", title: "Homenagem Dia das Profissões | UNoB", cat: "Institucional", q: "HD", video: "/media/videos/2026-09-23_diadasprofissoes_web_v01.mp4", preview: "/media/previews/2026-09-24_diadasprofissoes_preview_v01", desc: "Homenagem institucional ao Dia das Profissões, produzida para a União Noroeste Brasileira. Vídeo exibido direto do site." },
  // ── Dates verified directly from YouTube publish dates ──
  // Sort is automatic — just add new videos anywhere with the correct date field
  // IDs are stable unique identifiers (do not change them)
  { id: 26, date: "2026-09-18", title: "Dia Mundial dos Desbravadores | UNoB",       cat: "Institucional", q: "HD", img: "https://img.youtube.com/vi/lKI94t-ohCg/maxresdefault.jpg", url: "https://www.youtube.com/embed/lKI94t-ohCg", desc: "Homenagem ao Dia Mundial dos Desbravadores para a União Noroeste Brasileira: um chamado à fé, ao serviço e à coragem de quem ouve a voz de Deus." },
  { id: 27, date: "2026-06-19", title: "Três Gerações | Identidade Adventista",      cat: "Documentário", q: "4K", img: "https://img.youtube.com/vi/ON2z7dSBr1w/maxresdefault.jpg", url: "https://www.youtube.com/embed/ON2z7dSBr1w", desc: "Minidocumentário sobre Sara, Lena e Letícia: três gerações de uma família unidas pela mesma fé e pelo legado que passam adiante." },
  { id: 24, date: "2026-08-01", title: "Em Nome de Jesus (Releitura) | Quarteto Elo",   cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/i80kukSzjgQ/maxresdefault.jpg", url: "https://www.youtube.com/embed/i80kukSzjgQ", desc: "Releitura emocionante e cinematográfica com o Quarteto Elo, destacando harmonias vocais refinadas e direção de fotografia imersiva." },
  { id: 23, date: "2026-05-02", title: "Entrego a Ti | Gabriella Stehling",           cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/1YKP5mdZxoM/maxresdefault.jpg", url: "https://www.youtube.com/embed/1YKP5mdZxoM", desc: "Interpretação visual íntima e minimalista, explorando a iluminação suave e enquadramentos sensíveis que ressaltam a entrega emocional da performance." },
  { id: 1,  date: "2026-04-10", title: "Meu Respirar | Gabriella Stehling",          cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/WeBx8Ewkm4I/maxresdefault.jpg", url: "https://www.youtube.com/embed/WeBx8Ewkm4I", desc: "Produção cinematográfica com foco em texturas de luz e color grading dramático, elevando a adoração a um novo patamar visual." },
  { id: 2,  date: "2026-04-03", title: "Jeová Jireh | Gabriella Stehling",           cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/rQlMRuub6vo/maxresdefault.jpg", url: "https://www.youtube.com/embed/rQlMRuub6vo", desc: "Narrativa visual focada em minimalismo e elegância, destacando o protagonismo vocal com fotografia limpa e cortes sutis." },
  { id: 3,  date: "2026-03-27", title: "Tu És | Gabriella Stehling",                 cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/yrkck9BhKqo/maxresdefault.jpg", url: "https://www.youtube.com/embed/yrkck9BhKqo", desc: "Exploração de ângulos e profundidade de campo para criar uma experiência imersiva e espiritual de alta fidelidade visual." },
  { id: 4,  date: "2026-03-20", title: "Foi em Meu Lugar — Willian Krusty",          cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/MqIsul0I_to/maxresdefault.jpg",  url: "https://www.youtube.com/embed/MqIsul0I_to", desc: "Direção de arte e edição rítmica que traduzem a intensidade do sacrifício em imagens poderosas e cinematográficas." },
  { id: 5,  date: "2025-12-24", title: "Não Me Envergonho do Evangelho",             cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/ijf0p0naTcg/maxresdefault.jpg",  url: "https://www.youtube.com/embed/ijf0p0naTcg", desc: "Documentação visual de fé com estética editorial, equilibrando luz natural e composições de forte impacto emocional." },
  { id: 6,  date: "2025-12-03", title: "O Oráculo | Reality Show",                   cat: "Reality Show", q: "4K", img: "https://img.youtube.com/vi/efa_PSKMHLk/maxresdefault.jpg",  url: "https://www.youtube.com/embed/efa_PSKMHLk", desc: "Edição dinâmica para reality show, dominando o ritmo e o suspense para manter o engajamento do público cena a cena." },
  { id: 7,  date: "2025-10-31", title: "O Nome | Prisma Reunion – 45 Anos",          cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/bWVmk45mSl8/maxresdefault.jpg",  url: "https://www.youtube.com/embed/bWVmk45mSl8", desc: "Registro histórico e grandioso de um evento de legado, com multicâmera e tratamento de cor de altíssima gama." },
  { id: 8,  date: "2025-09-06", title: "Making Of | O Melhor de Mim",                cat: "Bastidores",   q: "HD", img: "https://img.youtube.com/vi/TD3uPps-RQ4/maxresdefault.jpg",  url: "https://www.youtube.com/embed/TD3uPps-RQ4", desc: "Captura de processos criativos e bastidores técnicos com olhar documental e narrativa orgânica de produção." },
  { id: 9,  date: "2025-08-22", title: "Gratidão — Dilson Castro",                   cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/0xftXOdbiDU/maxresdefault.jpg",  url: "https://www.youtube.com/embed/0xftXOdbiDU", desc: "Videoclipe com foco em storytelling visual e iluminação controlada, reforçando a mensagem lírica com excelência técnica." },
  { id: 11, date: "2025-08-20", title: "Continue em Frente (Ao Vivo) — Turnê 2025", cat: "Turnê",        q: "4K", img: "https://img.youtube.com/vi/g2MK7F0Adqc/maxresdefault.jpg",  url: "https://www.youtube.com/embed/g2MK7F0Adqc", desc: "Edição de show ao vivo com energia cinematográfica, sincronizando palco e atmosfera para uma experiência VIP." },
  { id: 12, date: "2025-08-08", title: "Lembra — Kati Carvalho feat. Communion",     cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/DAglqbQTK4c/maxresdefault.jpg",  url: "https://www.youtube.com/embed/DAglqbQTK4c", desc: "Parceria visual rica em detalhes e fotografia de alta performance, focada na harmonia entre artistas e ambiente." },
  { id: 13, date: "2025-08-08", title: "Hospedando Anjos Sem Saber (Ao Vivo 2025)",  cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/htIKc_vVDt0/maxresdefault.jpg",  url: "https://www.youtube.com/embed/htIKc_vVDt0", desc: "Experiência live session em 4K com foco em proximidade emocional e cortes que valorizam a performance instrumental e vocal." },
  { id: 14, date: "2025-06-27", title: "O Peso das Palavras | Curta Metragem",       cat: "Cinema",       q: "4K", img: "https://img.youtube.com/vi/h5vbvGte3oM/maxresdefault.jpg",  url: "https://www.youtube.com/embed/h5vbvGte3oM", desc: "Direção de fotografia e edição para cinema, explorando o silêncio e o subtexto através de uma narrativa visual densa." },
  { id: 15, date: "2024-12-03", title: "Making Of | Cicatrizes — Califórnia Dreams", cat: "Bastidores",   q: "4K", img: "https://img.youtube.com/vi/lJT58HZHD7g/maxresdefault.jpg",  url: "https://www.youtube.com/embed/lJT58HZHD7g", desc: "Documentário técnico de bastidores revelando a complexidade da produção e o cuidado de cada frame no set." },
  { id: 16, date: "2024-12-02", title: "Cicatrizes | Documentário — Califórnia Dreams", cat: "Documentário", q: "4K", img: "https://img.youtube.com/vi/NwesZCYbSx0/maxresdefault.jpg", url: "https://www.youtube.com/embed/NwesZCYbSx0", desc: "Narrativa documental profunda com estética cinematográfica, mesclando entrevistas e imagens B-roll de alto nível." },
  { id: 17, date: "2024-11-30", title: "Óh Quão Lindo Esse Nome É — Prisminha",     cat: "Clipes",       q: "4K", img: "https://img.youtube.com/vi/GWZWbLaovLY/maxresdefault.jpg",  url: "https://www.youtube.com/embed/GWZWbLaovLY", desc: "Produção delicada e lúdica focada em público infantil, mantendo o padrão 4K e a excelência editorial." },
  { id: 18, date: "2024-06-10", title: "Bárbara | Curta Metragem",                   cat: "Cinema",       q: "4K", img: "https://img.youtube.com/vi/p6SIYQ2c2Bw/maxresdefault.jpg",  url: "https://www.youtube.com/embed/p6SIYQ2c2Bw", desc: "Cinema independente com foco em atmosfera psicológica, usando luz e cor para construir a tensão narrativa." },
  { id: 20, date: "2024-05-04", title: "Patrícia de Paiva #1",                       cat: "Documentário", q: "4K", img: "https://img.youtube.com/vi/R8s2cjlf98k/maxresdefault.jpg",  url: "https://www.youtube.com/embed/R8s2cjlf98k", desc: "Perfis biográficos com olhar artístico, transformando histórias reais em experiências visuais memoráveis e inspiradoras." },
  { id: 21, date: "2023-12-07", title: "Saudade — Pedro Valença | Califórnia Dreams", cat: "Clipes",      q: "4K", img: "https://img.youtube.com/vi/Mul19Lfeo7Y/maxresdefault.jpg",  url: "https://www.youtube.com/embed/Mul19Lfeo7Y", desc: "Estética California Dreams com cores quentes e nostalgia visual, dominando a composição em cenários externos desafiadores." },
  { id: 22, date: "2023-06-15", title: "Nosso Jeito de Amar — Dunamis Studio",       cat: "Documentário", q: "HD", img: "https://img.youtube.com/vi/RRfgyZBCGn4/maxresdefault.jpg",  url: "https://www.youtube.com/embed/RRfgyZBCGn4", desc: "Documentação de estúdio focada em processos criativos, capturando a essência da música com proximidade e realismo." },
].sort((a, b) => new Date(b.date) - new Date(a.date));

